version: '3.5'

services:
  # MySQL container
  mysql:
    container_name: golarn-mysql
    image: mysql:8
    # restart: always
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  # phpMyAdmin container
  pma:
    container_name: golarn-pma
    image: phpmyadmin/phpmyadmin:latest
    # restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8080:80
    links:
      - mysql:db

  # memcached
  memcached:
    container_name: golarn-memcached
    image: memcached:1.5-alpine
    ports:
      - 11211:11211

  # dynamodb
  dynamodb:
    container_name: golarn-dynamodb
    build: ./docker/dynamodb
    volumes:
      - ./docker/dynamodb/db:/usr/local/dynamodb/db
    ports:
      - 8000:8000
